Add X-Ray

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -104,6 +104,22 @@ jobs:
         jf npm pack
         ls -lh ${{ env.TARBALL_PATH }}
 
+    - name: Scan package for vulnerabilities
+      run: |
+        if ! jf audit \
+          --format=table \
+          --npm \
+            --watches SecurityWatch \
+            --secrets \
+            --sca \
+            --sast \
+            --sbom \
+            --fail; then
+          echo "✗ ERROR: Vulnerabilities found in package"
+          echo "Please fix the vulnerabilities before publishing the package"
+          exit 1
+        fi
+
     - name: Publish to JFrog Artifactory
       run: |
         jf rt upload "${{ env.TARBALL_PATH }}" "${{ env.JFROG_REPO_NAME }}/" \
